apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
  labels:
    group: example
spec:  #spec for overall deployment
  replicas: 2
  selector: # required by k8 to match pods to deployments so this deployment know which pods should be controlled by it.
    matchLabels: #only apps matching both these labels will be controlled by this deployment, not just one or the other.
      app: first-app
      tier: backend   
      # matchExpressions: 
      #   - {key: app, operator: NotIn, values: [second-app, first-app]}
  template:  # templates always refer to pods
    metadata: 
      labels:
        app: first-app
        tier: backend
    spec: #spec for pods which are created for deployment
      containers:
        - name: first-node
          image: willnjl/kub-first-app:2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 3
            initialDelaySeconds: 5
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"  

