apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem #Filesytem || block storage types and filesystem are the two types of storage used in development
  accessModes:
    - ReadWriteOnce # Read and write access by one pod only
    # - ReadWriteMany # Read and write access by many pods
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data
    type: DirectoryOrCreate
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
