apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: 
    app: first-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
      tier: backend
  template:
    metadata: 
      labels:
        app: first-app
        tier: backend
    spec: 
      containers:
        - name: first-node
          image: willnjl/kub-first-app:2
        # - name: ...
        #   image: ...
