apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: #matchLabel not required as in deployments.yaml as it is the only availible option
    app: first-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer